### ISSUE TITLE
Error in process using the shell script

### ISSUE THREAD

**Issue by StephanM87** [JR-1991/software-driven-rdm#4]
## Metadata:

- OS: Windows 10
- branch: master (no change in sourcery/master)
- packages in setup.py were installed 

## Problem: 
I cloned the repository and tried to run the [shell script](https://github.com/JR-1991/software-driven-rdm/blob/master/Examples/Generation/generate_api.sh). Unfortunately I run into the following error:

```
sdrdm generate --path ./specifications --out . --name pyBioCat
Traceback (most recent call last):
  File "C:\Users\SMalz\anaconda3\Scripts\sdrdm-script.py", line 33, in <module>
    sys.exit(load_entry_point('sdRDM==0.0.2', 'console_scripts', 'sdrdm')())
  File "C:\Users\SMalz\anaconda3\Scripts\sdrdm-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\SMalz\anaconda3\lib\site-packages\importlib_metadata\__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "C:\Users\SMalz\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\SMalz\anaconda3\lib\site-packages\sdRDM\__init__.py", line 1, in <module>
    from .base.datamodel import DataModel
  File "C:\Users\SMalz\anaconda3\lib\site-packages\sdRDM\base\__init__.py", line 1, in <module>
    from .datamodel import DataModel
  File "C:\Users\SMalz\anaconda3\lib\site-packages\sdRDM\base\datamodel.py", line 283
    return roots, *modules
                  ^
SyntaxError: invalid syntax
```

**Comment by JR-1991** [comment]
Thanks for submitting the issue! You may need to update your installation, as the code from the error is from a previous version.

**Comment by StephanM87** [comment]
Yes, thanks a lot. I created a whole new conda environment and installed everything again.
