### ISSUE TITLE
HDF5 error with Python=3.11 when installing sdRDM

### ISSUE THREAD

**Issue by torogi94** [JR-1991/software-driven-rdm#42]
Trying to install sdRDM with Python=3.11 installed in the environment yields an error when building `tables`:

```shell
Collecting tables
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      ld: library not found for -llzo2
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library not found for -llzo
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library not found for -lblosc
      clang: error: linker command failed with exit code 1 (use -v to see invocation)

      Error compiling Cython file:
      ------------------------------------------------------------
      ...


      def _dump_h5_backtrace():
          cdef object bt = []

          if H5Ewalk(H5E_DEFAULT, H5E_WALK_DOWNWARD, e_walk_cb, <void*>bt) < 0:
                                                     ^
      ------------------------------------------------------------

      tables/utilsextension.pyx:384:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil'.
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ]
      * Found cython 3.0.2
      * USE_PKGCONFIG: False
      * Found conda env: ``/opt/homebrew/Caskroom/miniconda/base/envs/iranalysis``
      * Found HDF5 headers at ``/Users/torstengiess/HDF5-1.12.2-Darwin/HDF_Group/HDF5/1.12.2/include``, library at ``/Users/torstengiess/HDF5-1.12.2-Darwin/HDF_Group/HDF5/1.12.2/lib``.
      .. WARNING:: Could not find the HDF5 runtime.
         The HDF5 shared library was *not* found in the default library
         paths. In case of runtime problems, please remember to install it.
      * Could not find LZO 2 headers and library; disabling support for it.
      * Could not find LZO 1 headers and library; disabling support for it.
      * Found bzip2 headers at ``/opt/homebrew/Caskroom/miniconda/base/envs/iranalysis/include``, library at ``/opt/homebrew/Caskroom/miniconda/base/envs/iranalysis/lib``.
      * Could not find blosc headers and library; using internal sources.
      * Found blosc2 headers at ``/private/var/folders/wp/l9gzqd2d0_l1t60lv307d2s00000gn/T/pip-build-env-1l3ww1be/overlay/include``, library at ``/private/var/folders/wp/l9gzqd2d0_l1t60lv307d2s00000gn/T/pip-build-env-1l3ww1be/overlay/lib``.
        * Copying blosc2 runtime library to 'tables' dir because it was not found in standard locations
      Compiling tables/utilsextension.pyx because it changed.
      [1/1] Cythonizing tables/utilsextension.pyx
      Traceback (most recent call last):
        File "/opt/homebrew/Caskroom/miniconda/base/envs/iranalysis/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/Caskroom/miniconda/base/envs/iranalysis/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Caskroom/miniconda/base/envs/iranalysis/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wp/l9gzqd2d0_l1t60lv307d2s00000gn/T/pip-build-env-1l3ww1be/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/wp/l9gzqd2d0_l1t60lv307d2s00000gn/T/pip-build-env-1l3ww1be/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/wp/l9gzqd2d0_l1t60lv307d2s00000gn/T/pip-build-env-1l3ww1be/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 928, in <module>
        File "<string>", line 923, in get_cython_extfiles
        File "/private/var/folders/wp/l9gzqd2d0_l1t60lv307d2s00000gn/T/pip-build-env-1l3ww1be/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/wp/l9gzqd2d0_l1t60lv307d2s00000gn/T/pip-build-env-1l3ww1be/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

This behaviour does not occur with Python=3.10 or lower.

**Comment by fbergmann** [comment]
I was struggling with this as well, but finally managed, to get this to install using pytables right from git, so I think the next release will fix it: 

```bash
git clone https://github.com/PyTables/PyTables
cd PyTables
HDF5_DIR=/opt/homebrew/opt/hdf5 BLOSC_DIR=/opt/homebrew/opt/c-blosc LZO_DIR=/opt/homebrew/opt/lzo BZIP2_DIR=/opt/homebrew/opt/bzip2 pip install .
...
0f35dfcf4014944b2
Successfully built tables
Installing collected packages: py-cpuinfo, tables
Successfully installed py-cpuinfo-9.0.0 tables-3.8.1.dev0
```

**Comment by JR-1991** [comment]
Opened a PR to fix this and other issues - #43
